//! Per-species wood appearance, loaded from `core/data/wood_appearance.json`.
//!
//! That file is generated by `tools/wood-fit/export_appearance.py` (private repo)
//! from photo-fitted, by-eye-reviewed parameters. Keys match presets.json
//! `materials.woods`; keys without their own entry resolve through `aliases`, then
//! fall back to `default` (the synthetic generic wood).

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::sync::OnceLock;

const WOOD_APPEARANCE_JSON: &str = include_str!("../../../data/wood_appearance.json");

/// Colors for the grain layers (hex).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WoodPalette {
    /// Face color
    pub base: String,
    /// Ring traces, zone bands and pores
    pub late: String,
    /// Color-variation streaks
    pub streak: String,
    /// Light patches and ray flecks
    pub alt: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Figure {
    /// Plain-sawn: rings around a tilted pith (arches, or near-straight flanks)
    Cathedral,
    /// Quartersawn: near-straight ring lines plus ray flecks
    Quarter,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LineMode {
    /// Diffuse-porous woods and softwoods
    Continuous,
    /// Long irregular dashes (walnut, mahogany)
    Broken,
    /// Ring-porous oak/ash: rings show only as pore bands
    None,
}

/// Anatomy-driven structure (decided per species, not fitted).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WoodStructure {
    pub figure: Figure,
    pub line_mode: LineMode,
    /// +1: zone band on the earlywood side of each ring (ring-porous pore band);
    /// -1: latewood side (softwood latewood band)
    pub zone_side: i8,
    pub pores: bool,
    pub flecks: bool,
}

/// Numeric generator knobs. Lengths in inches; opacities 0..1. Defaults mirror the
/// prototype's `gen_fit.DEFAULTS`, so a partial JSON entry still renders.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct WoodParams {
    pub rings_per_in: f64,
    pub ring_cv: f64,
    pub pith_depth_in: f64,
    pub pith_tilt: f64,
    pub pith_offset_in: f64,
    pub depth_noise_in: f64,
    pub line_w_in: f64,
    pub line_op: f64,
    pub wiggle_in: f64,
    pub wiggle_len_in: f64,
    pub pore_rows: u32,
    pub pore_band_in: f64,
    pub pore_band_frac: Option<f64>,
    pub pore_len_in: f64,
    pub pore_gap_in: f64,
    pub pore_w_in: f64,
    pub pore_op: f64,
    pub pore_jitter: f64,
    pub pore_rows_by_width: bool,
    pub fleck_arc_spacing_in: f64,
    pub fleck_arc_curv: f64,
    pub fleck_len_in: f64,
    pub fleck_len_sd: f64,
    pub fleck_gap_in: f64,
    pub fleck_aspect: f64,
    pub fleck_op: f64,
    pub streak_op: f64,
    pub streak_soft: bool,
    pub streak_patchy: bool,
    pub zone_op: f64,
    pub zone_frac: f64,
    pub zone_break: f64,
    pub line_dash_in: f64,
    pub line_gap_in: f64,
    pub line_thick_var: f64,
    pub ribbon: bool,
    pub apex_widen_cap: f64,
    pub thick_noise: f64,
    /// Extra darkness of the vertical pieces (flat faces; grain at 90° reflects differently)
    pub grain_tone: f64,
}

impl Default for WoodParams {
    fn default() -> Self {
        Self {
            rings_per_in: 8.0, ring_cv: 0.38, pith_depth_in: 1.4, pith_tilt: 0.065, pith_offset_in: 0.6,
            depth_noise_in: 0.35, line_w_in: 0.015, line_op: 0.5, wiggle_in: 0.02, wiggle_len_in: 1.6,
            pore_rows: 3, pore_band_in: 0.03, pore_band_frac: None, pore_len_in: 0.1, pore_gap_in: 0.3,
            pore_w_in: 0.012, pore_op: 0.5, pore_jitter: 0.0, pore_rows_by_width: false,
            fleck_arc_spacing_in: 0.6, fleck_arc_curv: 0.8, fleck_len_in: 0.5, fleck_len_sd: 0.45,
            fleck_gap_in: 0.4, fleck_aspect: 0.17, fleck_op: 0.5,
            streak_op: 0.35, streak_soft: false, streak_patchy: false,
            zone_op: 0.0, zone_frac: 0.45, zone_break: 0.0,
            line_dash_in: 0.6, line_gap_in: 0.9, line_thick_var: 0.0,
            ribbon: false, apex_widen_cap: 2.0, thick_noise: 0.35, grain_tone: 0.05,
        }
    }
}

/// One species' look.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WoodAppearance {
    pub palette: WoodPalette,
    pub structure: WoodStructure,
    #[serde(default)]
    pub params: WoodParams,
    /// Reviewed spans per knob, for per-frame variation (not used yet)
    #[serde(default)]
    pub per_frame_range: BTreeMap<String, [f64; 2]>,
    /// Figure variants (e.g. white oak "quartersawn")
    #[serde(default)]
    pub variants: BTreeMap<String, WoodAppearance>,
}

#[derive(Debug, Deserialize)]
struct AppearanceFile {
    default: String,
    #[serde(default)]
    aliases: BTreeMap<String, String>,
    woods: BTreeMap<String, WoodAppearance>,
}

fn data() -> &'static AppearanceFile {
    static DATA: OnceLock<AppearanceFile> = OnceLock::new();
    DATA.get_or_init(|| serde_json::from_str(WOOD_APPEARANCE_JSON).expect("wood_appearance.json is valid"))
}

/// Appearance for a `materials.woods` key (alias, then default fallback), optionally a
/// figure variant such as `"quartersawn"` (falls back to the base look if absent).
pub fn wood_appearance(key: &str, variant: Option<&str>) -> &'static WoodAppearance {
    let d = data();
    let key = d.aliases.get(key).map(String::as_str).unwrap_or(key);
    let base = d.woods.get(key).unwrap_or_else(|| &d.woods[&d.default]);
    variant.and_then(|v| base.variants.get(v)).unwrap_or(base)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_presets_wood_resolves() {
        for key in crate::presets::get_materials().woods.keys() {
            let a = wood_appearance(key, None);
            assert!(a.palette.base.starts_with('#'), "{key}");
        }
    }

    #[test]
    fn appearance_keys_are_presets_woods() {
        let woods = &crate::presets::get_materials().woods;
        for key in data().woods.keys().chain(data().aliases.keys()) {
            assert!(woods.contains_key(key), "{key} is not a materials.woods key");
        }
    }

    #[test]
    fn aliases_and_variants_resolve() {
        let generic = wood_appearance("generic", None);
        assert_eq!(wood_appearance("generic_hardwood", None).palette.base, generic.palette.base);
        assert_eq!(wood_appearance("mdf_moulding", None).palette.base, generic.palette.base, "default fallback");
        let qs = wood_appearance("white_oak", Some("quartersawn"));
        assert_eq!(qs.structure.figure, Figure::Quarter);
        assert!(qs.structure.flecks);
        assert_eq!(wood_appearance("white_oak", Some("nope")).structure.figure, Figure::Cathedral);
    }

    #[test]
    fn ring_porous_species_have_no_ring_line() {
        for key in ["red_oak", "white_oak", "white_ash"] {
            assert_eq!(wood_appearance(key, None).structure.line_mode, LineMode::None, "{key}");
        }
    }
}
