//! Per-species wood appearance, loaded from `core/data/wood_appearance.json`.
//!
//! That file is generated by `tools/wood-fit/export_appearance.py` (private repo)
//! from photo-fitted, by-eye-reviewed parameters. Keys match presets.json
//! `materials.woods`; keys without their own entry resolve through `aliases`, then
//! fall back to `default` (the synthetic generic wood).

use super::noise::mix32;
use serde::{Deserialize, Serialize};
use std::borrow::Cow;
use std::collections::BTreeMap;
use std::sync::OnceLock;

const WOOD_APPEARANCE_JSON: &str = include_str!("../../../data/wood_appearance.json");

/// Colors for the grain layers (hex).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WoodPalette {
    /// Face color
    pub base: String,
    /// Ring traces, zone bands and pores
    pub late: String,
    /// Color-variation streaks
    pub streak: String,
    /// Light patches and ray flecks
    pub alt: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Figure {
    /// Plain-sawn: rings around a tilted pith (arches, or near-straight flanks)
    Cathedral,
    /// Quartersawn: near-straight ring lines plus ray flecks
    Quarter,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LineMode {
    /// Diffuse-porous woods and softwoods
    Continuous,
    /// Long irregular dashes (walnut, mahogany)
    Broken,
    /// Ring-porous oak/ash: rings show only as pore bands
    None,
}

/// Anatomy-driven structure (decided per species, not fitted).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WoodStructure {
    pub figure: Figure,
    pub line_mode: LineMode,
    /// +1: zone band on the earlywood side of each ring (ring-porous pore band);
    /// -1: latewood side (softwood latewood band)
    pub zone_side: i8,
    pub pores: bool,
    pub flecks: bool,
}

/// Numeric generator knobs. Lengths in inches; opacities 0..1. Defaults mirror the
/// prototype's `gen_fit.DEFAULTS`, so a partial JSON entry still renders.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct WoodParams {
    pub rings_per_in: f64,
    pub ring_cv: f64,
    pub pith_depth_in: f64,
    pub pith_tilt: f64,
    pub pith_offset_in: f64,
    pub depth_noise_in: f64,
    pub line_w_in: f64,
    pub line_op: f64,
    pub wiggle_in: f64,
    pub wiggle_len_in: f64,
    pub pore_rows: u32,
    pub pore_band_in: f64,
    pub pore_band_frac: Option<f64>,
    pub pore_len_in: f64,
    pub pore_gap_in: f64,
    pub pore_w_in: f64,
    pub pore_op: f64,
    pub pore_jitter: f64,
    pub pore_rows_by_width: bool,
    pub fleck_arc_spacing_in: f64,
    pub fleck_arc_curv: f64,
    pub fleck_len_in: f64,
    pub fleck_len_sd: f64,
    pub fleck_gap_in: f64,
    pub fleck_aspect: f64,
    pub fleck_op: f64,
    pub streak_op: f64,
    pub streak_soft: bool,
    pub streak_patchy: bool,
    pub zone_op: f64,
    pub zone_frac: f64,
    pub zone_break: f64,
    pub line_dash_in: f64,
    pub line_gap_in: f64,
    pub line_thick_var: f64,
    pub ribbon: bool,
    pub apex_widen_cap: f64,
    pub thick_noise: f64,
    /// Extra darkness of the vertical pieces (flat faces; grain at 90° reflects differently)
    pub grain_tone: f64,
}

impl Default for WoodParams {
    fn default() -> Self {
        Self {
            rings_per_in: 8.0, ring_cv: 0.38, pith_depth_in: 1.4, pith_tilt: 0.065, pith_offset_in: 0.6,
            depth_noise_in: 0.35, line_w_in: 0.015, line_op: 0.5, wiggle_in: 0.02, wiggle_len_in: 1.6,
            pore_rows: 3, pore_band_in: 0.03, pore_band_frac: None, pore_len_in: 0.1, pore_gap_in: 0.3,
            pore_w_in: 0.012, pore_op: 0.5, pore_jitter: 0.0, pore_rows_by_width: false,
            fleck_arc_spacing_in: 0.6, fleck_arc_curv: 0.8, fleck_len_in: 0.5, fleck_len_sd: 0.45,
            fleck_gap_in: 0.4, fleck_aspect: 0.17, fleck_op: 0.5,
            streak_op: 0.35, streak_soft: false, streak_patchy: false,
            zone_op: 0.0, zone_frac: 0.45, zone_break: 0.0,
            line_dash_in: 0.6, line_gap_in: 0.9, line_thick_var: 0.0,
            ribbon: false, apex_widen_cap: 2.0, thick_noise: 0.35, grain_tone: 0.05,
        }
    }
}

/// Lighter or darker colouring of a species (same boards, same grain).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WoodTone {
    /// Unfinished: toward the sanded reference photo (paler, less amber)
    Light,
    /// The fitted palette (between the sanded and finished photos)
    #[default]
    Natural,
    /// Toward the finished reference photo (richer, deeper)
    Dark,
}

/// Tone palettes, derived offline per species (`tools/wood-fit/tones.py`).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WoodTones {
    pub light: WoodPalette,
    pub dark: WoodPalette,
}

/// Ring spacing varies by up to this fraction either way on a reshuffled board (it has
/// no reviewed `per_frame_range`; held near the photo's value).
const RINGS_SPREAD: f64 = 0.1;

/// One species' look.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WoodAppearance {
    pub palette: WoodPalette,
    pub structure: WoodStructure,
    #[serde(default)]
    pub params: WoodParams,
    /// Reviewed spans per knob (the top-3 by-eye picks); a reshuffled board draws
    /// each knob within its span (see [`WoodAppearance::styled`])
    #[serde(default)]
    pub per_frame_range: BTreeMap<String, [f64; 2]>,
    /// Lighter and darker palettes
    #[serde(default)]
    pub tones: Option<WoodTones>,
    /// Figure variants (e.g. white oak "quartersawn")
    #[serde(default)]
    pub variants: BTreeMap<String, WoodAppearance>,
}

impl WoodAppearance {
    /// The palette for a tone (the natural one if the species has no tones).
    pub fn palette_for(&self, tone: WoodTone) -> &WoodPalette {
        match (tone, &self.tones) {
            (WoodTone::Light, Some(t)) => &t.light,
            (WoodTone::Dark, Some(t)) => &t.dark,
            _ => &self.palette,
        }
    }

    /// This look in `tone`, with its knobs varied when `vary` is given: each
    /// `per_frame_range` knob is drawn within its span and the ring spacing within
    /// +-[`RINGS_SPREAD`], deterministically from the seed. Borrowed (unchanged) for the
    /// natural tone without variation.
    pub fn styled(&self, tone: WoodTone, vary: Option<u32>) -> Cow<'_, WoodAppearance> {
        if tone == WoodTone::Natural && vary.is_none() {
            return Cow::Borrowed(self);
        }
        let mut params = self.params.clone();
        if let Some(seed) = vary {
            // a uniform draw in [0, 1) per knob, independent of the others
            let unit = |key: &str| {
                let h = key.bytes().fold(seed, |h, b| mix32(h ^ u32::from(b)));
                f64::from(mix32(h) >> 8) / f64::from(1u32 << 24)
            };
            params.rings_per_in *= 1.0 + RINGS_SPREAD * (2.0 * unit("rings_per_in") - 1.0);
            // through JSON so the ranges can name any knob (integer knobs stay integral)
            if let Ok(serde_json::Value::Object(mut map)) = serde_json::to_value(&params) {
                for (key, &[lo, hi]) in &self.per_frame_range {
                    let v = lo + (hi - lo) * unit(key);
                    let integral = map.get(key).is_some_and(|x| x.is_u64());
                    map.insert(key.clone(), if integral { serde_json::json!(v.round() as u64) } else { serde_json::json!(v) });
                }
                if let Ok(p) = serde_json::from_value(serde_json::Value::Object(map)) {
                    params = p;
                }
            }
        }
        Cow::Owned(WoodAppearance {
            palette: self.palette_for(tone).clone(),
            structure: self.structure.clone(),
            params,
            per_frame_range: BTreeMap::new(),
            tones: None,
            variants: BTreeMap::new(),
        })
    }
}

#[derive(Debug, Deserialize)]
struct AppearanceFile {
    default: String,
    #[serde(default)]
    aliases: BTreeMap<String, String>,
    woods: BTreeMap<String, WoodAppearance>,
}

fn data() -> &'static AppearanceFile {
    static DATA: OnceLock<AppearanceFile> = OnceLock::new();
    DATA.get_or_init(|| serde_json::from_str(WOOD_APPEARANCE_JSON).expect("wood_appearance.json is valid"))
}

/// Appearance for a `materials.woods` key (alias, then default fallback), optionally a
/// figure variant such as `"quartersawn"` (falls back to the base look if absent).
pub fn wood_appearance(key: &str, variant: Option<&str>) -> &'static WoodAppearance {
    let d = data();
    let key = d.aliases.get(key).map(String::as_str).unwrap_or(key);
    let base = d.woods.get(key).unwrap_or_else(|| &d.woods[&d.default]);
    variant.and_then(|v| base.variants.get(v)).unwrap_or(base)
}

/// The `materials.woods` keys with a look of their own (the default first, then the
/// rest alphabetically). The others (aliases and unlisted keys) draw as the default.
pub fn wood_looks() -> Vec<&'static str> {
    let d = data();
    std::iter::once(d.default.as_str())
        .chain(d.woods.keys().map(String::as_str).filter(|k| *k != d.default))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn looks_exclude_aliases_and_fallbacks() {
        let looks = wood_looks();
        assert_eq!(looks[0], "generic");
        assert!(looks.contains(&"red_oak") && looks.contains(&"douglas_fir"));
        for key in ["generic_hardwood", "generic_softwood", "mdf_moulding", "finger_jointed_pine"] {
            assert!(!looks.contains(&key), "{key}");
        }
    }

    #[test]
    fn every_presets_wood_resolves() {
        for key in crate::presets::get_materials().woods.keys() {
            let a = wood_appearance(key, None);
            assert!(a.palette.base.starts_with('#'), "{key}");
        }
    }

    #[test]
    fn appearance_keys_are_presets_woods() {
        let woods = &crate::presets::get_materials().woods;
        for key in data().woods.keys().chain(data().aliases.keys()) {
            assert!(woods.contains_key(key), "{key} is not a materials.woods key");
        }
    }

    #[test]
    fn every_look_has_tones() {
        for key in wood_looks() {
            let a = wood_appearance(key, None);
            let t = a.tones.as_ref().unwrap_or_else(|| panic!("{key} has no tones"));
            assert_ne!(t.light.base, a.palette.base, "{key}");
            assert_ne!(t.dark.base, a.palette.base, "{key}");
        }
        assert!(wood_appearance("white_oak", Some("quartersawn")).tones.is_some());
    }

    #[test]
    fn natural_unvaried_look_is_borrowed() {
        let a = wood_appearance("red_oak", None);
        assert!(matches!(a.styled(WoodTone::Natural, None), Cow::Borrowed(_)));
        let dark = a.styled(WoodTone::Dark, None);
        assert_eq!(dark.palette.base, a.tones.as_ref().unwrap().dark.base);
        assert_eq!(dark.params.rings_per_in, a.params.rings_per_in);
    }

    #[test]
    fn varied_knobs_stay_in_their_reviewed_spans() {
        for key in wood_looks() {
            let a = wood_appearance(key, None);
            let base = serde_json::to_value(&a.params).unwrap();
            let mut moved = 0;
            for seed in 0..40u32 {
                let v = a.styled(WoodTone::Natural, Some(mix32(seed)));
                assert_eq!(v.palette.base, a.palette.base);
                let r = v.params.rings_per_in / a.params.rings_per_in;
                assert!((1.0 - RINGS_SPREAD..=1.0 + RINGS_SPREAD).contains(&r), "{key} rings x{r}");
                let p = serde_json::to_value(&v.params).unwrap();
                for (knob, &[lo, hi]) in &a.per_frame_range {
                    let x = p[knob].as_f64().unwrap();
                    // integer knobs round to the nearest
                    assert!(x >= lo - 0.5 && x <= hi + 0.5, "{key} {knob}={x} not in [{lo}, {hi}]");
                    if p[knob] != base[knob] {
                        moved += 1;
                    }
                }
            }
            assert!(a.per_frame_range.is_empty() || moved > 0, "{key}: nothing varied");
        }
    }

    #[test]
    fn variation_is_deterministic() {
        let a = wood_appearance("black_walnut", None);
        let (x, y) = (a.styled(WoodTone::Light, Some(7)), a.styled(WoodTone::Light, Some(7)));
        assert_eq!(serde_json::to_string(&x.params).unwrap(), serde_json::to_string(&y.params).unwrap());
        let z = a.styled(WoodTone::Light, Some(8));
        assert_ne!(serde_json::to_string(&x.params).unwrap(), serde_json::to_string(&z.params).unwrap());
    }

    #[test]
    fn aliases_and_variants_resolve() {
        let generic = wood_appearance("generic", None);
        assert_eq!(wood_appearance("generic_hardwood", None).palette.base, generic.palette.base);
        assert_eq!(wood_appearance("mdf_moulding", None).palette.base, generic.palette.base, "default fallback");
        let qs = wood_appearance("white_oak", Some("quartersawn"));
        assert_eq!(qs.structure.figure, Figure::Quarter);
        assert!(qs.structure.flecks);
        assert_eq!(wood_appearance("white_oak", Some("nope")).structure.figure, Figure::Cathedral);
    }

    #[test]
    fn ring_porous_species_have_no_ring_line() {
        for key in ["red_oak", "white_oak", "white_ash"] {
            assert_eq!(wood_appearance(key, None).structure.line_mode, LineMode::None, "{key}");
        }
    }
}
